spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${dev-db.postgres.host}:${dev-db.postgres.port}/${dev-db.postgres.name}
    username: ${dev-db.postgres.username}
    password: ${dev-db.postgres.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: validate
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true

  data:
    mongodb:
      uri: mongodb+srv://${dev-db.mongo.username}:${dev-db.mongo.password}@${dev-db.mongo.host}/?retryWrites=true&w=majority&appName=${dev-db.mongo.database}
      database: ${dev-db.mongo.database}

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.data.mongodb.core.MongoTemplate: debug
#    org.springframework.data.mongodb.core.convert: debug
#    org.springframework.data.mongodb.core.query: debug
#    org.springframework.transaction.interceptor: trace
