spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${local-db.postgres.host}:${local-db.postgres.port}/${local-db.postgres.name}
    username: ${local-db.postgres.username}
    password: ${local-db.postgres.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl.auto: create
        default_batch_fetch_size: 100
    open-in-view: false
    show-sql: true

  data:
    mongodb:
      uri: mongodb://${local-db.mongo.username}:${local-db.mongo.password}@${local-db.mongo.host}:${local-db.mongo.port}/?retryWrites=true&w=majority&appName=${local-db.mongo.database}
      database: ${local-db.mongo.database}

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.data.mongodb.core.MongoTemplate: debug
#    org.springframework.data.mongodb.core.convert: debug
#    org.springframework.data.mongodb.core.query: debug
#    org.springframework.transaction.interceptor: trace
