spring:
  datasource:
    meta:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${dev-db.postgres.meta-db.host}:${dev-db.postgres.meta-db.port}/${dev-db.postgres.meta-db.name}
        username: ${dev-db.postgres.meta-db.username}
        password: ${dev-db.postgres.meta-db.password}

    domain:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://${dev-db.postgres.domain-db.host}:${dev-db.postgres.domain-db.port}/${dev-db.postgres.domain-db.name}
        username: ${dev-db.postgres.domain-db.username}
        password: ${dev-db.postgres.domain-db.password}

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
    open-in-view: false

  data:
    mongodb:
      uri: mongodb+srv://${dev-db.mongo.username}:${dev-db.mongo.password}@${dev-db.mongo.host}/?retryWrites=true&w=majority&appName=${dev-db.mongo.database}
      database: ${dev-db.mongo.database}
