spring:
  profiles:
    default: local

  config:
    import:
      - security/application-db.yml

  batch:
    job:
      name: statisticJob
      enabled: true
    jdbc:
      initialize-schema: always
